// Import videos explicitly to avoid caching issues
const lx4toursVideo = require('@/assets/videos/lx4tours.mp4');
const puppybondVideo = require('@/assets/videos/puppybond_1.mp4');
const escala25Video = require('@/assets/videos/escala25.mp4');

export interface Experience {
  id: string;
  title: string;
  provider: string;
  providerLogo?: any;
  location: string;
  distance: string;
  price: number;
  currency: string;
  duration: string;
  rating: number;
  reviewCount: number;
  image: string;
  video?: any;
  images?: any[];
  category: string;
  tags: string[];
  description: string;
  highlights: string[];
  included: string[];
  meetingPoint: string;
  latitude: number;
  longitude: number;
  availableToday: boolean;
  instantBooking: boolean;
  verified: boolean;
  maxGroupSize?: number;
  languages?: string[];
  whatToBring?: string[];
  cancellationPolicy?: string;
  importantInfo?: string;
}

export const EXPERIENCES: Experience[] = [
  {
    id: '1',
    title: 'Atlantic Coast Guided Quad Bike Tour',
    provider: 'LX4Tours',
    providerLogo: require('@/assets/images/lxtourslogo.png'),
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 99,
    currency: '€',
    duration: '2h',
    rating: 5.0,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    video: lx4toursVideo,
    images: [
      require('@/assets/images/lxtours1.png'),
      require('@/assets/images/lxtours2.png'),
      require('@/assets/images/lxtours3.png'),
      require('@/assets/images/lxtours4.png'),
    ],
    category: 'Outdoors',
    tags: ['Quad Bikes', 'Beach', 'Off-Road', 'Nature', 'Sports', 'Outdoors'],
    description: 'Explore the wild side of Lisbon on a relaxed and guided quad bike tour. Embark on an immersive adventure and discover secret places, unknown stories and local culture. Navigate quiet roads to build confidence on your quad bike. Feel the wind in your face as you head to an abandoned WWI military complex built to protect the gates of Europe.',
    highlights: [
      'Explore the wild side of Lisbon',
      'Learn about Portuguese history, myths and legends',
      'Unlock exclusive access to hidden places, inaccessible any other way',
      'Take amazing photos and videos with incredible views',
      'Discover the local community and learn about their culture',
      'Visit the Portuguese Grand Canyon - as old as time itself',
      'See an abandoned 1980s water park hidden on top of the canyon',
      'Discover a 16th century monastery built by a mysterious Portuguese family',
      'Face challenging trails while driving through the forest',
    ],
    included: [
      'Quad bike tour',
      'Professional guide',
      'Safety instructions',
      'Protective equipment (helmet & gear)',
      'Health insurance',
    ],
    meetingPoint: 'R. Frei Bartolomeu Assunção 15, Costa de Caparica - Look for the Portuguese flag on a white wall, red barrels and blue containers',
    latitude: 38.63798904418945,
    longitude: -9.231167793273926,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
    languages: ['Portuguese', 'English', 'French'],
    whatToBring: ['Driver\'s license'],
    cancellationPolicy: 'Free cancellation up to 24 hours in advance for a full refund',
    importantInfo: 'Drivers can switch multiple times during the tour. The passenger experience is also an adventure in itself. This description refers to the most common route used on this tour. The itinerary may differ from tour to tour depending on various factors.',
  },
  {
    id: '2',
    title: 'Puppy Yoga - Relaxa e Conecta-te com Cachorros',
    provider: 'Puppy Bond',
    providerLogo: require('@/assets/images/pupyylogo.webp'),
    location: 'Lisboa',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '1h15',
    rating: 5.0,
    reviewCount: 2,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    video: puppybondVideo,
    images: [
      require('@/assets/images/puppy1.webp'),
      require('@/assets/images/puppy2.webp'),
      require('@/assets/images/puppy3.webp'),
      require('@/assets/images/puppy4.webp'),
    ],
    category: 'Mind & Body',
    tags: ['Yoga', 'Animals', 'Wellness', 'Relax', 'Unique', 'Sports', 'Mind & Body', 'Do Good'],
    description: 'Puppy Yoga brings together the best of both worlds: the benefits of yoga and the contagious joy of puppies. It\'s a unique experience, perfect for relaxing, improving your well-being, and experiencing moments full of affection.',
    highlights: [
      'Reduce stress and anxiety through breathing and relaxation techniques',
      'Increase happiness — interacting with puppies releases serotonin and endorphins',
      'Strengthen your body and gain flexibility, even if you\'re new to yoga',
      'Improve concentration and posture, bringing more balance to your daily life',
      'Feel the emotional comfort of contact with animals, a true wellness therapy',
      'Discover a different activity, ideal for doing alone or with friends',
      'Contribute to responsible dog adoption',
    ],
    included: [
      '15 minutes to interact with the puppies at the start',
      '45 minutes of guided yoga',
      '15 minutes at the end for photos and more interaction',
      'All yoga materials',
      'Insurance',
    ],
    meetingPoint: 'Various locations in Lisbon - confirmed after booking',
    latitude: 38.7223,
    longitude: -9.1393,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 20,
    languages: ['Portuguese', 'English'],
    whatToBring: ['Comfortable clothes for yoga', 'Water', 'Yoga mat (optional)'],
    cancellationPolicy: 'Free cancellation up to 24 hours before the session for a full refund',
    importantInfo: 'Part of each ticket price is donated to animal protection associations. Some dogs may be available for responsible adoption.',
  },
  {
    id: '3',
    title: 'Experiência de Escalada Guiada na Ponte 25 de Abril',
    provider: 'Escala25',
    providerLogo: require('@/assets/images/escala25logo.jpeg'),
    location: 'Lisboa - Ponte 25 de Abril',
    distance: '5km away',
    price: 30,
    currency: '€',
    duration: '1h',
    rating: 4.9,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    video: escala25Video,
    images: [
      require('@/assets/images/escala251.jpg'),
      require('@/assets/images/escala252.jpg'),
      require('@/assets/images/escala253.jpg'),
      require('@/assets/images/escala254.jpg'),
    ],
    category: 'Outdoors',
    tags: ['Climbing', 'Outdoor', 'Sports', 'Adrenaline', 'Bridge', 'Outdoors'],
    description: 'Visit one of Lisbon\'s premier outdoor adventures and climb one of the city\'s most iconic structures, the 25 de Abril Bridge. Learn the basics of climbing, bouldering, and self-belaying, or join the intermediate level course and improve your knowledge of knot work.',
    highlights: [
      'Feel the adrenaline of climbing the imposing 25 de Abril Bridge in Lisbon',
      'Learn the basics of climbing and familiarize yourself with bouldering and self-belaying',
      'Spend the day exploring the climbing facilities of the 25 de Abril Bridge on your own',
      'Choose between a beginner climbing class or an intermediate level introduction course',
      'Learn the ins and outs of climbing fundamentals, such as knot work and ropes',
      'Multiple climbing routes up to 40 feet (12 meters) high',
    ],
    included: [
      '1 hour climbing course',
      'Safety equipment',
      'Access to bouldering and auto-belay areas',
      'Professional instructor',
    ],
    meetingPoint: 'Pilar 7 Experience - Av. da Índia, Lisbon. From the parking lot, head to reception to collect your ticket.',
    latitude: 38.70038604736328,
    longitude: -9.178533554077148,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
    languages: ['Portuguese', 'English'],
    whatToBring: ['Sunscreen', 'Water', 'Comfortable clothing'],
    cancellationPolicy: 'Free cancellation up to 24 hours in advance for a full refund',
    importantInfo: 'This activity involves climbing to heights of up to 40 feet (12 meters). Not suitable for children under 6 years, people with reduced mobility, or those over 95 years old.',
  },
  {
    id: '3',
    title: 'Secret Food Tour: Alfama',
    provider: 'Taste of Lisboa',
    location: 'Lisbon',
    distance: '0.8km away',
    price: 75,
    currency: '€',
    duration: '3.5h',
    rating: 5.0,
    reviewCount: 341,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Food', 'Culture', 'Local'],
    description: 'Discover the hidden culinary gems of Alfama. Taste authentic Portuguese dishes while exploring narrow cobblestone streets and local secrets.',
    highlights: [
      'Visit 6 authentic local spots',
      'Try traditional Portuguese dishes',
      'Learn about local culture & history',
      'Small groups (max 10 people)'
    ],
    included: ['Food & drinks', 'Expert local guide', 'Secret locations'],
    meetingPoint: 'Miradouro de Santa Luzia',
    latitude: 38.7115,
    longitude: -9.1281,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '4',
    title: 'Surf Lesson at Costa da Caparica',
    provider: 'Atlantic Surf School',
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 35,
    currency: '€',
    duration: '2h',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800&q=80',
    category: 'Adventure',
    tags: ['Surf', 'Beach', 'Active'],
    description: 'Learn to surf on one of Portugal\'s best beaches. Professional instructors will have you riding waves in no time!',
    highlights: [
      'Perfect for beginners',
      'All equipment provided',
      'Certified instructors',
      'Beautiful Atlantic beach'
    ],
    included: ['Surfboard', 'Wetsuit', 'Insurance', 'Photos'],
    meetingPoint: 'Praia do Surf, Costa da Caparica',
    latitude: 38.6333,
    longitude: -9.2333,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '5',
    title: 'Fado Night Experience',
    provider: 'Casa do Fado',
    location: 'Bairro Alto',
    distance: '1.5km away',
    price: 55,
    currency: '€',
    duration: '2.5h',
    rating: 4.9,
    reviewCount: 278,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    category: 'Music & Culture',
    tags: ['Music', 'Culture', 'Evening'],
    description: 'Experience authentic Fado music in an intimate traditional venue. Includes dinner and Portuguese wine.',
    highlights: [
      'Live Fado performance',
      'Traditional Portuguese dinner',
      'Historic venue',
      'Wine included'
    ],
    included: ['3-course dinner', 'Wine', 'Live music', 'Reserved seating'],
    meetingPoint: 'Rua da Rosa 123, Bairro Alto',
    latitude: 38.7142,
    longitude: -9.1459,
    availableToday: true,
    instantBooking: false,
    verified: true,
  },
  {
    id: '6',
    title: 'Street Art Walking Tour',
    provider: 'Urban Art Lisboa',
    location: 'LX Factory',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '2h',
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80',
    category: 'Art & Culture',
    tags: ['Art', 'Urban', 'Photography'],
    description: 'Explore Lisbon\'s vibrant street art scene. Discover hidden murals and learn about the artists behind them.',
    highlights: [
      'Visit famous street art spots',
      'Learn about local artists',
      'Great for photography',
      'Off-the-beaten-path locations'
    ],
    included: ['Expert guide', 'Map of art locations', 'Coffee break'],
    meetingPoint: 'LX Factory Main Entrance',
    latitude: 38.7029,
    longitude: -9.1794,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '7',
    title: 'E-Bike Tour: 7 Hills of Lisbon',
    provider: 'Lisbon Bike Tours',
    location: 'Baixa',
    distance: '0.5km away',
    price: 50,
    currency: '€',
    duration: '3h',
    rating: 4.8,
    reviewCount: 224,
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80',
    category: 'Tours',
    tags: ['Active', 'Sightseeing', 'E-bike'],
    description: 'Conquer Lisbon\'s famous seven hills effortlessly on an electric bike. See all major landmarks in one tour.',
    highlights: [
      'Visit all 7 hills',
      'Electric bikes (no sweat!)',
      'See 15+ landmarks',
      'Small group size'
    ],
    included: ['E-bike', 'Helmet', 'Guide', 'Water'],
    meetingPoint: 'Praça do Comércio',
    latitude: 38.7071,
    longitude: -9.1365,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '8',
    title: 'Wine Tasting in Sintra',
    provider: 'Quinta da Regaleira',
    location: 'Sintra',
    distance: '28km away',
    price: 85,
    currency: '€',
    duration: '4h',
    rating: 5.0,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Wine', 'Nature', 'Day Trip'],
    description: 'Escape to the magical hills of Sintra for an exclusive wine tasting at a historic quinta. Includes transport from Lisbon.',
    highlights: [
      'Taste 6 premium Portuguese wines',
      'Visit historic estate',
      'Gourmet cheese pairing',
      'Round-trip transport included'
    ],
    included: ['Transport', 'Wine tasting', 'Cheese board', 'Tour guide'],
    meetingPoint: 'Rossio Train Station (or hotel pickup)',
    latitude: 38.7969,
    longitude: -9.3897,
    availableToday: false,
    instantBooking: false,
    verified: true,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All', icon: '🎯' },
  { id: 'local-cooking', name: 'Local Cooking', icon: '🍳' },
  { id: 'culture-dive', name: 'Culture Dive', icon: '🎭' },
  { id: 'outdoors', name: 'Outdoors', icon: '🏔️' },
  { id: 'sports', name: 'Sports', icon: '⚽' },
  { id: 'micro-adventures', name: 'Micro Adventures', icon: '🗺️' },
  { id: 'night-explorer', name: 'Night Explorer', icon: '🌙' },
  { id: 'do-good', name: 'Do Good', icon: '❤️' },
  { id: 'mind-body', name: 'Mind & Body', icon: '🧘' },
  { id: 'learn-create', name: 'Learn & Create', icon: '🎨' },
  { id: 'time-stories', name: 'Time Stories', icon: '📖' },
];
