// Import videos explicitly to avoid caching issues
const lx4toursVideo = require('@/assets/videos/lx4tours.mp4');
const puppybondVideo = require('@/assets/videos/puppybond_1.mp4');
const escala25Video = require('@/assets/videos/escala25.mp4');

export interface Experience {
  id: string;
  title: string;
  provider: string;
  providerLogo?: any;
  location: string;
  distance: string;
  price: number;
  currency: string;
  duration: string;
  rating: number;
  reviewCount: number;
  image: string;
  video?: any;
  images?: any[];
  category: string;
  tags: string[];
  description: string;
  highlights: string[];
  included: string[];
  meetingPoint: string;
  latitude: number;
  longitude: number;
  availableToday: boolean;
  instantBooking: boolean;
  verified: boolean;
  maxGroupSize?: number;
  languages?: string[];
  whatToBring?: string[];
  cancellationPolicy?: string;
  importantInfo?: string;
}

export const EXPERIENCES: Experience[] = [
  {
    id: '1',
    title: 'Atlantic Coast Guided Quad Bike Tour',
    provider: 'LX4Tours',
    providerLogo: require('@/assets/images/lxtourslogo.png'),
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 99,
    currency: '€',
    duration: '2h',
    rating: 5.0,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    video: lx4toursVideo,
    images: [
      require('@/assets/images/lxtours1.png'),
      require('@/assets/images/lxtours2.png'),
      require('@/assets/images/lxtours3.png'),
      require('@/assets/images/lxtours4.png'),
    ],
    category: 'Outdoors',
    tags: ['Quad Bikes', 'Beach', 'Off-Road', 'Nature', 'Sports', 'Outdoors'],
    description: 'Explore the wild side of Lisbon on a relaxed and guided quad bike tour. Embark on an immersive adventure and discover secret places, unknown stories and local culture. Navigate quiet roads to build confidence on your quad bike. Feel the wind in your face as you head to an abandoned WWI military complex built to protect the gates of Europe.',
    highlights: [
      'Explore the wild side of Lisbon',
      'Learn about Portuguese history, myths and legends',
      'Unlock exclusive access to hidden places, inaccessible any other way',
      'Take amazing photos and videos with incredible views',
      'Discover the local community and learn about their culture',
      'Visit the Portuguese Grand Canyon - as old as time itself',
      'See an abandoned 1980s water park hidden on top of the canyon',
      'Discover a 16th century monastery built by a mysterious Portuguese family',
      'Face challenging trails while driving through the forest',
    ],
    included: [
      'Quad bike tour',
      'Professional guide',
      'Safety instructions',
      'Protective equipment (helmet & gear)',
      'Health insurance',
    ],
    meetingPoint: 'R. Frei Bartolomeu Assunção 15, Costa de Caparica - Look for the Portuguese flag on a white wall, red barrels and blue containers',
    latitude: 38.63798904418945,
    longitude: -9.231167793273926,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
    languages: ['Portuguese', 'English', 'French'],
    whatToBring: ['Driver\'s license'],
    cancellationPolicy: 'Free cancellation up to 24 hours in advance for a full refund',
    importantInfo: 'Drivers can switch multiple times during the tour. The passenger experience is also an adventure in itself. This description refers to the most common route used on this tour. The itinerary may differ from tour to tour depending on various factors.',
  },
  {
    id: '2',
    title: 'Puppy Yoga - Relaxa e Conecta-te com Cachorros',
    provider: 'Puppy Bond',
    providerLogo: require('@/assets/images/pupyylogo.webp'),
    location: 'Lisboa',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '1h15',
    rating: 5.0,
    reviewCount: 2,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    video: puppybondVideo,
    images: [
      require('@/assets/images/puppy1.webp'),
      require('@/assets/images/puppy2.webp'),
      require('@/assets/images/puppy3.webp'),
      require('@/assets/images/puppy4.webp'),
    ],
    category: 'Mind & Body',
    tags: ['Yoga', 'Animals', 'Wellness', 'Relax', 'Unique', 'Sports', 'Mind & Body', 'Do Good'],
    description: 'Puppy Yoga brings together the best of both worlds: the benefits of yoga and the contagious joy of puppies. It\'s a unique experience, perfect for relaxing, improving your well-being, and experiencing moments full of affection.',
    highlights: [
      'Reduce stress and anxiety through breathing and relaxation techniques',
      'Increase happiness — interacting with puppies releases serotonin and endorphins',
      'Strengthen your body and gain flexibility, even if you\'re new to yoga',
      'Improve concentration and posture, bringing more balance to your daily life',
      'Feel the emotional comfort of contact with animals, a true wellness therapy',
      'Discover a different activity, ideal for doing alone or with friends',
      'Contribute to responsible dog adoption',
    ],
    included: [
      '15 minutes to interact with the puppies at the start',
      '45 minutes of guided yoga',
      '15 minutes at the end for photos and more interaction',
      'All yoga materials',
      'Insurance',
    ],
    meetingPoint: 'Various locations in Lisbon - confirmed after booking',
    latitude: 38.7223,
    longitude: -9.1393,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 20,
    languages: ['Portuguese', 'English'],
    whatToBring: ['Comfortable clothes for yoga', 'Water', 'Yoga mat (optional)'],
    cancellationPolicy: 'Free cancellation up to 24 hours before the session for a full refund',
    importantInfo: 'Part of each ticket price is donated to animal protection associations. Some dogs may be available for responsible adoption.',
  },
  {
    id: '3',
    title: 'Experiência de Escalada Guiada na Ponte 25 de Abril',
    provider: 'Escala25',
    providerLogo: require('@/assets/images/escala25logo.jpeg'),
    location: 'Lisboa - Ponte 25 de Abril',
    distance: '5km away',
    price: 30,
    currency: '€',
    duration: '1h',
    rating: 4.9,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    video: escala25Video,
    images: [
      require('@/assets/images/escala251.jpg'),
      require('@/assets/images/escala252.jpg'),
      require('@/assets/images/escala253.jpg'),
      require('@/assets/images/escala254.jpg'),
    ],
    category: 'Outdoors',
    tags: ['Climbing', 'Outdoor', 'Sports', 'Adrenaline', 'Bridge', 'Outdoors'],
    description: 'Visit one of Lisbon\'s premier outdoor adventures and climb one of the city\'s most iconic structures, the 25 de Abril Bridge. Learn the basics of climbing, bouldering, and self-belaying, or join the intermediate level course and improve your knowledge of knot work.',
    highlights: [
      'Feel the adrenaline of climbing the imposing 25 de Abril Bridge in Lisbon',
      'Learn the basics of climbing and familiarize yourself with bouldering and self-belaying',
      'Spend the day exploring the climbing facilities of the 25 de Abril Bridge on your own',
      'Choose between a beginner climbing class or an intermediate level introduction course',
      'Learn the ins and outs of climbing fundamentals, such as knot work and ropes',
      'Multiple climbing routes up to 40 feet (12 meters) high',
    ],
    included: [
      '1 hour climbing course',
      'Safety equipment',
      'Access to bouldering and auto-belay areas',
      'Professional instructor',
    ],
    meetingPoint: 'Pilar 7 Experience - Av. da Índia, Lisbon. From the parking lot, head to reception to collect your ticket.',
    latitude: 38.70038604736328,
    longitude: -9.178533554077148,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
    languages: ['Portuguese', 'English'],
    whatToBring: ['Sunscreen', 'Water', 'Comfortable clothing'],
    cancellationPolicy: 'Free cancellation up to 24 hours in advance for a full refund',
    importantInfo: 'This activity involves climbing to heights of up to 40 feet (12 meters). Not suitable for children under 6 years, people with reduced mobility, or those over 95 years old.',
  },
  {
    id: '3',
    title: 'Secret Food Tour: Alfama',
    provider: 'Taste of Lisboa',
    location: 'Lisbon',
    distance: '0.8km away',
    price: 75,
    currency: '€',
    duration: '3.5h',
    rating: 5.0,
    reviewCount: 341,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Food', 'Culture', 'Local'],
    description: 'Discover the hidden culinary gems of Alfama. Taste authentic Portuguese dishes while exploring narrow cobblestone streets and local secrets.',
    highlights: [
      'Visit 6 authentic local spots',
      'Try traditional Portuguese dishes',
      'Learn about local culture & history',
      'Small groups (max 10 people)'
    ],
    included: ['Food & drinks', 'Expert local guide', 'Secret locations'],
    meetingPoint: 'Miradouro de Santa Luzia',
    latitude: 38.7115,
    longitude: -9.1281,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '4',
    title: 'Surf Lesson at Costa da Caparica',
    provider: 'Atlantic Surf School',
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 35,
    currency: '€',
    duration: '2h',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800&q=80',
    category: 'Adventure',
    tags: ['Surf', 'Beach', 'Active'],
    description: 'Learn to surf on one of Portugal\'s best beaches. Professional instructors will have you riding waves in no time!',
    highlights: [
      'Perfect for beginners',
      'All equipment provided',
      'Certified instructors',
      'Beautiful Atlantic beach'
    ],
    included: ['Surfboard', 'Wetsuit', 'Insurance', 'Photos'],
    meetingPoint: 'Praia do Surf, Costa da Caparica',
    latitude: 38.6333,
    longitude: -9.2333,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '5',
    title: 'Fado Night Experience',
    provider: 'Casa do Fado',
    location: 'Bairro Alto',
    distance: '1.5km away',
    price: 55,
    currency: '€',
    duration: '2.5h',
    rating: 4.9,
    reviewCount: 278,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    category: 'Music & Culture',
    tags: ['Music', 'Culture', 'Evening'],
    description: 'Experience authentic Fado music in an intimate traditional venue. Includes dinner and Portuguese wine.',
    highlights: [
      'Live Fado performance',
      'Traditional Portuguese dinner',
      'Historic venue',
      'Wine included'
    ],
    included: ['3-course dinner', 'Wine', 'Live music', 'Reserved seating'],
    meetingPoint: 'Rua da Rosa 123, Bairro Alto',
    latitude: 38.7142,
    longitude: -9.1459,
    availableToday: true,
    instantBooking: false,
    verified: true,
  },
  {
    id: '6',
    title: 'Street Art Walking Tour',
    provider: 'Urban Art Lisboa',
    location: 'LX Factory',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '2h',
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80',
    category: 'Art & Culture',
    tags: ['Art', 'Urban', 'Photography'],
    description: 'Explore Lisbon\'s vibrant street art scene. Discover hidden murals and learn about the artists behind them.',
    highlights: [
      'Visit famous street art spots',
      'Learn about local artists',
      'Great for photography',
      'Off-the-beaten-path locations'
    ],
    included: ['Expert guide', 'Map of art locations', 'Coffee break'],
    meetingPoint: 'LX Factory Main Entrance',
    latitude: 38.7029,
    longitude: -9.1794,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '7',
    title: 'E-Bike Tour: 7 Hills of Lisbon',
    provider: 'Lisbon Bike Tours',
    location: 'Baixa',
    distance: '0.5km away',
    price: 50,
    currency: '€',
    duration: '3h',
    rating: 4.8,
    reviewCount: 224,
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80',
    category: 'Tours',
    tags: ['Active', 'Sightseeing', 'E-bike'],
    description: 'Conquer Lisbon\'s famous seven hills effortlessly on an electric bike. See all major landmarks in one tour.',
    highlights: [
      'Visit all 7 hills',
      'Electric bikes (no sweat!)',
      'See 15+ landmarks',
      'Small group size'
    ],
    included: ['E-bike', 'Helmet', 'Guide', 'Water'],
    meetingPoint: 'Praça do Comércio',
    latitude: 38.7071,
    longitude: -9.1365,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '8',
    title: 'Wine Tasting in Sintra',
    provider: 'Quinta da Regaleira',
    location: 'Sintra',
    distance: '28km away',
    price: 85,
    currency: '€',
    duration: '4h',
    rating: 5.0,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Wine', 'Nature', 'Day Trip'],
    description: 'Escape to the magical hills of Sintra for an exclusive wine tasting at a historic quinta. Includes transport from Lisbon.',
    highlights: [
      'Taste 6 premium Portuguese wines',
      'Visit historic estate',
      'Gourmet cheese pairing',
      'Round-trip transport included'
    ],
    included: ['Transport', 'Wine tasting', 'Cheese board', 'Tour guide'],
    meetingPoint: 'Rossio Train Station (or hotel pickup)',
    latitude: 38.7969,
    longitude: -9.3897,
    availableToday: false,
    instantBooking: false,
    verified: true,
  },
  {
    id: '4',
    title: 'Dolphin Watching Experience',
    provider: 'Atlantic Dolphin Tours',
    location: 'Setúbal',
    distance: '40km away',
    price: 45,
    currency: '€',
    duration: '3h',
    rating: 4.9,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    category: 'Outdoors',
    tags: ['Nature', 'Marine Life', 'Adventure'],
    description: 'Join us for an unforgettable dolphin watching experience in the beautiful waters of Setúbal. See dolphins in their natural habitat!',
    highlights: [
      'See wild dolphins up close',
      'Expert marine biologists on board',
      'Beautiful coastal views',
      'Small group experience'
    ],
    included: ['Boat tour', 'Guide', 'Binoculars', 'Photos'],
    meetingPoint: 'Porto de Setúbal',
    latitude: 38.5245,
    longitude: -8.8926,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '10',
    title: 'Horses by the Beach',
    provider: 'Coastal Equestrian',
    location: 'Costa da Caparica',
    distance: '18km away',
    price: 65,
    currency: '€',
    duration: '1.5h',
    rating: 5.0,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80',
    category: 'Outdoors',
    tags: ['Horses', 'Beach', 'Nature'],
    description: 'Experience the magic of horseback riding along the stunning Atlantic coastline. Perfect for all skill levels.',
    highlights: [
      'Ride along pristine beaches',
      'Suitable for beginners',
      'Professional instructors',
      'Minimum 2 people required'
    ],
    included: ['Horse', 'Safety equipment', 'Guide', 'Insurance'],
    meetingPoint: 'Praia da Sereia, Costa da Caparica',
    latitude: 38.6250,
    longitude: -9.2400,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
  },
  {
    id: '11',
    title: 'Azulejos Design Workshop',
    provider: 'Tile Art Studio',
    location: 'Chiado',
    distance: '2km away',
    price: 55,
    currency: '€',
    duration: '2h',
    rating: 4.8,
    reviewCount: 203,
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80',
    category: 'Learn & Create',
    tags: ['Art', 'Culture', 'Hands-on'],
    description: 'Learn the traditional Portuguese art of tile painting. Create your own azulejo masterpiece to take home!',
    highlights: [
      'Learn traditional techniques',
      'Create your own tile',
      'Take your creation home',
      'Professional artist instruction'
    ],
    included: ['Materials', 'Tile to keep', 'Refreshments', 'Guide'],
    meetingPoint: 'Rua do Crucifixo 112, Chiado',
    latitude: 38.7109,
    longitude: -9.1413,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 12,
  },
  {
    id: '5',
    title: 'Natelier Art Experience',
    provider: 'Natelier Studio',
    location: 'Santos',
    distance: '3km away',
    price: 40,
    currency: '€',
    duration: '2h',
    rating: 4.9,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80',
    category: 'Learn & Create',
    tags: ['Art', 'Creative', 'Workshop'],
    description: 'Explore your creative side in this hands-on art workshop. Perfect for both beginners and experienced artists.',
    highlights: [
      'All materials provided',
      'Expert instruction',
      'Take your artwork home',
      'Relaxed atmosphere'
    ],
    included: ['Art supplies', 'Refreshments', 'Guide', 'Your artwork'],
    meetingPoint: 'Rua de Santos 45',
    latitude: 38.7065,
    longitude: -9.1520,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
  },
  {
    id: '9',
    title: 'Souldreamers Experience',
    provider: 'Souldreamers',
    location: 'Cascais',
    distance: '25km away',
    price: 70,
    currency: '€',
    duration: '2h',
    rating: 5.0,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80',
    category: 'Mind & Body',
    tags: ['Wellness', 'Mindfulness', 'Relaxation'],
    description: 'A unique wellness experience combining meditation, sound healing, and coastal views. Reconnect with yourself.',
    highlights: [
      'Sound healing session',
      'Guided meditation',
      'Ocean views',
      'Small intimate groups'
    ],
    included: ['Meditation mat', 'Sound therapy', 'Herbal tea', 'Guide'],
    meetingPoint: 'Praia da Rainha, Cascais',
    latitude: 38.6979,
    longitude: -9.4204,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 15,
  },
  {
    id: '7',
    title: 'Spinach Tours Food Experience',
    provider: 'Spinach Tours',
    location: 'Alfama',
    distance: '1km away',
    price: 60,
    currency: '€',
    duration: '3h',
    rating: 4.9,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Food', 'Culture', 'Local'],
    description: 'Discover Lisbon\'s culinary secrets on this guided food tour through historic Alfama. Taste authentic Portuguese flavors!',
    highlights: [
      'Visit 6+ local eateries',
      'Taste traditional dishes',
      'Learn about food culture',
      'Small group experience'
    ],
    included: ['Food tastings', 'Drinks', 'Guide', 'Walking tour'],
    meetingPoint: 'Largo do Chafariz de Dentro, Alfama',
    latitude: 38.7131,
    longitude: -9.1289,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 12,
  },
  {
    id: '17',
    title: 'Rodas ao Vento - Buggy Adventure',
    provider: 'Rodas ao Vento',
    location: 'Arrábida',
    distance: '35km away',
    price: 90,
    currency: '€',
    duration: '1h',
    rating: 5.0,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    category: 'Adventure',
    tags: ['Buggy', 'Off-road', 'Adrenaline'],
    description: 'Experience the thrill of driving a buggy through stunning landscapes. Price is per buggy (fits 2 people).',
    highlights: [
      'Drive your own buggy',
      'Scenic mountain routes',
      'Professional instruction',
      'Price per buggy (2 people)'
    ],
    included: ['Buggy rental', 'Safety gear', 'Guide', 'Insurance'],
    meetingPoint: 'Estrada Nacional 379, Arrábida',
    latitude: 38.4833,
    longitude: -8.9833,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
  },
  {
    id: '12',
    title: 'Beekeeping Experience and Honey Tasting',
    provider: 'Farm Experience',
    location: 'Sintra',
    distance: '30km away',
    price: 79,
    currency: '€',
    duration: '3h',
    rating: 4.9,
    reviewCount: 45,
    image: 'https://images.unsplash.com/photo-1558642891-54be180ea339?w=800&q=80',
    category: 'Learn & Create',
    tags: ['Nature', 'Beekeeping', 'Farm', 'Honey'],
    description: 'Learn about beekeeping and taste delicious honey at a local farm in Sintra. A hands-on experience with nature.',
    highlights: [
      'Meet the beekeeper',
      'Learn about bee life',
      'Honey tasting session',
      'Farm tour included'
    ],
    included: ['Bee suit', 'Honey tasting', 'Farm tour', 'Guide'],
    meetingPoint: 'Farm near Sintra',
    latitude: 38.7969,
    longitude: -9.3897,
    availableToday: false,
    instantBooking: false,
    verified: true,
    maxGroupSize: 10,
  },
  {
    id: '13',
    title: 'Epic Full-Day Sintra Adventure',
    provider: 'Flamingo Experiences',
    location: 'Sintra',
    distance: '28km away',
    price: 59,
    currency: '€',
    duration: '7h',
    rating: 4.9,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    category: 'Outdoors',
    tags: ['Adventure', '4x4', 'Sintra', 'Full Day'],
    description: 'Epic full-day adventure through Sintra in a vintage 4x4 vehicle. Discover hidden spots and stunning landscapes.',
    highlights: [
      'Vintage 4x4 experience',
      'Hidden Sintra locations',
      'Wine tasting included',
      'Small group experience'
    ],
    included: ['4x4 transport', 'Guide', 'Wine tasting', 'Snacks'],
    meetingPoint: 'Sintra Center',
    latitude: 38.7969,
    longitude: -9.3897,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
  },
  {
    id: '14',
    title: 'One Day Pilot Experience',
    provider: 'Aero Dreams',
    location: 'Cascais Aerodrome',
    distance: '25km away',
    price: 199,
    currency: '€',
    duration: '1.5h',
    rating: 5.0,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    category: 'Adventure',
    tags: ['Flying', 'Pilot', 'Aviation', 'Unique'],
    description: 'Be a pilot for a day! Fly a real aircraft with an instructor. Unforgettable aviation experience.',
    highlights: [
      'Fly a real aircraft',
      'Professional instructor',
      'Certificate included',
      'Stunning coastal views'
    ],
    included: ['Flight time', 'Instructor', 'Certificate', 'Insurance'],
    meetingPoint: 'Cascais Aerodrome',
    latitude: 38.7249,
    longitude: -9.3553,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 1,
  },
  {
    id: '15',
    title: 'Indoor Skydiving - Dream Fly',
    provider: 'Dream Fly',
    location: 'Lisbon',
    distance: '5km away',
    price: 69,
    currency: '€',
    duration: '1h',
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    category: 'Adventure',
    tags: ['Skydiving', 'Indoor', 'Adrenaline', 'Unique'],
    description: 'Experience the thrill of skydiving without jumping from a plane! Indoor wind tunnel flying.',
    highlights: [
      'Safe indoor skydiving',
      'No experience needed',
      'Professional instructors',
      'All equipment provided'
    ],
    included: ['Equipment', 'Instructor', 'Photos', 'Insurance'],
    meetingPoint: 'Dream Fly Center, Lisbon',
    latitude: 38.7223,
    longitude: -9.1393,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
  },
  {
    id: '18',
    title: 'Surf Lesson - Duck Dive',
    provider: 'Duck Dive Surf School',
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 45,
    currency: '€',
    duration: '2h',
    rating: 4.9,
    reviewCount: 456,
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
    category: 'Sports',
    tags: ['Surf', 'Beach', 'Active', 'Water Sports'],
    description: 'Learn to surf with professional instructors at Costa da Caparica. Perfect for beginners and intermediates.',
    highlights: [
      'Professional instructors',
      'All equipment included',
      'Small groups',
      'Beautiful beach location'
    ],
    included: ['Surfboard', 'Wetsuit', 'Instructor', 'Insurance'],
    meetingPoint: 'Duck Dive Surf School, Praia da Caparica',
    latitude: 38.6333,
    longitude: -9.2333,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
  },
  {
    id: '19',
    title: '6 Day Beginner to Advanced Surf and Yoga Camp',
    provider: 'Roots Surf Camp',
    location: 'Ericeira',
    distance: '50km away',
    price: 479,
    currency: '€',
    duration: '6 Days',
    rating: 5.0,
    reviewCount: 123,
    image: 'https://images.unsplash.com/photo-1459289279437-cbf3f5f29b60?w=800&q=80',
    category: 'Sports',
    tags: ['Surf', 'Yoga', 'Retreat', 'Multi-Day'],
    description: '6-day surf and yoga camp in beautiful Ericeira. Perfect blend of surfing, yoga, and relaxation.',
    highlights: [
      '6 days of surf lessons',
      'Daily yoga sessions',
      'Accommodation included',
      'Healthy meals provided'
    ],
    included: ['6 nights accommodation', 'Surf lessons', 'Yoga classes', 'Meals', 'Equipment'],
    meetingPoint: 'Roots Surf Camp, Ericeira',
    latitude: 38.9636,
    longitude: -9.4159,
    availableToday: false,
    instantBooking: false,
    verified: true,
    maxGroupSize: 15,
  },
  {
    id: '20',
    title: 'Paragliding Adventure',
    provider: 'Fly With Us',
    location: 'Arrábida',
    distance: '40km away',
    price: 89,
    currency: '€',
    duration: '1h',
    rating: 5.0,
    reviewCount: 287,
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    category: 'Adventure',
    tags: ['Paragliding', 'Flying', 'Aerial', 'Adrenaline'],
    description: 'Soar above the stunning Arrábida mountains and coastline. Tandem paragliding with experienced pilots.',
    highlights: [
      'Tandem paragliding flight',
      'Stunning coastal views',
      'Professional pilot',
      'Photos and videos included'
    ],
    included: ['Paragliding equipment', 'Pilot', 'Insurance', 'Photos'],
    meetingPoint: 'Arrábida Natural Park',
    latitude: 38.4833,
    longitude: -8.9833,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 2,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All', icon: '🎯' },
  { id: 'local-cooking', name: 'Local Cooking', icon: '🍳' },
  { id: 'culture-dive', name: 'Culture Dive', icon: '🎭' },
  { id: 'outdoors', name: 'Outdoors', icon: '🏔️' },
  { id: 'sports', name: 'Sports', icon: '⚽' },
  { id: 'micro-adventures', name: 'Micro Adventures', icon: '🗺️' },
  { id: 'night-explorer', name: 'Night Explorer', icon: '🌙' },
  { id: 'do-good', name: 'Do Good', icon: '❤️' },
  { id: 'mind-body', name: 'Mind & Body', icon: '🧘' },
  { id: 'learn-create', name: 'Learn & Create', icon: '🎨' },
  { id: 'time-stories', name: 'Time Stories', icon: '📖' },
];
